packaging_format = 2

id = "writefreely"
name = "WriteFreely"
description.en = "For starting a minimalist, federated blog or an entire community"
description.fr = "Permet de créer un blog fédéré minimaliste ou une communauté entière"

version = "0.17.0~ynh1"

maintainers = ["trendless"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://writefreely.org"
demo = "https://write.as/new"
userdoc = "https://writefreely.org/start"
code = "https://github.com/writeas/writefreely"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["arm64", "amd64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.single_user]
    ask.en = "Choose if you want a Single User Blog?"
    ask.fr = "Souhaitez vous un blog pour un seul utilisateur ?"
    type = "boolean"
    default = true

[resources]
    [resources.sources]
        [resources.sources.main]
        arm64.url = "https://github.com/writefreely/writefreely/releases/download/v0.17.0/writefreely_0.17.0_linux_arm64.tar.gz"
        arm64.sha256 = "274e8fe91ed868539bc9824c449a3b3f3b7592e8d91e9e077e0f0faeeacf4789"
        amd64.url = "https://github.com/writefreely/writefreely/releases/download/v0.17.0/writefreely_0.17.0_linux_amd64.tar.gz"
        amd64.sha256 = "5e0caeabb889eb1c0c6c00cdf4fe67e498b3045c64e17374113ab21f7e1fc8a2"
        armhf.url = "https://github.com/writefreely/writefreely/releases/download/v0.17.0/writefreely_0.17.0_linux_arm7.tar.gz"
        armhf.sha256 = "93d7e563930dbf04613a75af005e6eff54383986e013a3b438eb849de531cabd"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^writefreely_.*_linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^writefreely_.*_linux_amd64.tar.gz$"
        autoupdate.asset.armhf = "^writefreely_.*_linux_arm7.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed= "visitors"
    api.auth_header= false
    api.show_tile= false
    api.protected= true

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
