packaging_format = 2

id = "writefreely"
name = "WriteFreely"
description.en = "For starting a minimalist, federated blog or an entire community"
description.fr = "Permet de créer un blog fédéré minimaliste ou une communauté entière"

version = "0.17.1~ynh1"

maintainers = ["trendless"]

[upstream]
license = "AGPL-3.0-or-later"
website = "https://writefreely.org"
demo = "https://write.as/new"
userdoc = "https://writefreely.org/start"
code = "https://github.com/writeas/writefreely"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["arm64", "amd64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "150M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.single_user]
    ask.en = "Choose if you want a Single User Blog?"
    ask.fr = "Souhaitez vous un blog pour un seul utilisateur ?"
    type = "boolean"
    default = true

[resources]
    [resources.sources]
        [resources.sources.main]
        arm64.url = "https://github.com/writefreely/writefreely/releases/download/v0.17.1/writefreely_0.17.1_linux_arm64.tar.gz"
        arm64.sha256 = "8bd6b23742becd663f97d25592784d6d329c5a63e09a09bb8dceeff268e756b5"
        amd64.url = "https://github.com/writefreely/writefreely/releases/download/v0.17.1/writefreely_0.17.1_linux_amd64.tar.gz"
        amd64.sha256 = "b3314ecce0f4b5d15b240b20f06cd8f200aea5f7a4274d64017de20d09cdad26"
        armhf.url = "https://github.com/writefreely/writefreely/releases/download/v0.17.1/writefreely_0.17.1_linux_arm7.tar.gz"
        armhf.sha256 = "631f9d0beed1471db41395ea02e10ac1edadda7a1e09f028ec28518f6bdc8f74"

        autoupdate.strategy = "latest_github_release"
        autoupdate.asset.arm64 = "^writefreely_.*_linux_arm64.tar.gz$"
        autoupdate.asset.amd64 = "^writefreely_.*_linux_amd64.tar.gz$"
        autoupdate.asset.armhf = "^writefreely_.*_linux_arm7.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed= "visitors"
    api.auth_header= false
    api.show_tile= false
    api.protected= true

    [resources.apt]
    packages = "mariadb-server"

    [resources.database]
    type = "mysql"
