test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
    args.single_user = true

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.acf26fb.name = "Upgrade from 0.16.0~ynh3"
    test_upgrade_from.cef1d17.name = "Upgrade from 0.17.0~ynh1"
