#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# BACKUP WRITEFREELY INSTALL DIRECTORY
#=================================================

ynh_print_info "Backing up $app install directory ($install_dir)..."

ynh_backup "$install_dir"

#=================================================
# BACKUP MYSQL DATABASE
#=================================================

ynh_print_info "Backing up database..."

ynh_mysql_dump_db > db.sql

#=================================================
# BACKUP SYSTEM CONFIGURATION
#=================================================

ynh_print_info "Backing up web server and system service files..."

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup complete. Make sure to test it!"
