#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app system service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# RECONFIGURE NGINX
#=================================================

ynh_script_progression "Updating web server to serve $app on $new_domain..."

ynh_config_change_url_nginx

#=================================================
# RECONFIGURE WRITEFREELY
#=================================================

ynh_script_progression "Updating $app configuration..."

ynh_backup_if_checksum_is_different "$install_dir/config.ini"

ynh_write_var_in_file --file="$install_dir/config.ini" --key="host" --value="https://$new_domain" --after="site_description"

# Recalculate and store the checksum of the file for the next upgrade.
ynh_store_file_checksum "$install_dir/config.ini"

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app system service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Serving on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "URL change complete."
