#!/bin/bash

if [ -n "$(uname -m | grep x86_64)" ]; then
	architecture="x86-64"
elif [ -n "$(uname -m | grep 86)" ]; then
	architecture="i386"
elif [ -n "$(uname -m | grep arm)" ]; then
	architecture="arm"
elif [ -n "$(uname -m | grep aarch64)" ]; then
	architecture="arm"
else
	ynh_die --message="Unable to detect your achitecture, please open a bug describing \
        your hardware and the result of the command \"uname -m\"." 1
fi
