#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

if ynh_in_ci_tests; then
	admin="test"
fi

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Configuring NGINX web server..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="WriteFreely daemon" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template="config.ini" --destination="$install_dir/config.ini"

chmod 600 "$install_dir/config.ini"

#=================================================
# MAKE SETUP
#=================================================
ynh_script_progression "Making setup..."

pushd $install_dir
	ynh_exec_as_app ./writefreely --init-db
	ynh_exec_as_app ./writefreely --gen-keys
	ynh_exec_as_app ./writefreely --create-admin "$admin":"$password"
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Serving on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
