#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app system service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Updating source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace=1 --keep=config.ini

#=================================================
# UPDATE SYSTEM CONFIGURATION
#=================================================

ynh_script_progression "Updating web server and system service configuration..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="WriteFreely daemon" --log="/var/log/$app/$app.log"

#=================================================
# MAKE THE UPGRADE
#=================================================

ynh_script_progression "Upgrading $app..."

pushd $install_dir
	ynh_mysql_db_shell <<< "ALTER DATABASE $db_name CHARACTER SET latin1 COLLATE latin1_swedish_ci;"

	ynh_exec_as_app ./writefreely db migrate
	ynh_exec_as_app ./writefreely --migrate
	ynh_exec_as_app ./writefreely keys generate
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app system service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Serving on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade complete."
