#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================

ynh_script_progression "Stopping $app system service..."

ynh_systemctl --service=$app --action="stop" --log_path="systemd"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

ynh_script_progression "Updating source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace=1 --keep=config.ini

#=================================================
# ADJUST CONFIG.INI SMTP_ENABLE_START_TLS VALUE
#=================================================

if ynh_app_upgrading_from_version_before_or_equal_to 0.16.0~ynh2; then
	ynh_script_progression "getting smtp variables..."
	smtp_host=$(ynh_read_var_in_file --file=$install_dir/config.ini --key=smtp_host)
	smtp_port=$(ynh_read_var_in_file --file=$install_dir/config.ini --key=smtp_port)
	smtp_enable_start_tls=$(ynh_read_var_in_file --file=$install_dir/config.ini --key=smtp_enable_start_tls)
	if $smtp_enable_start_tls=true && $smtp_port=25 && $smtp_host=127.0.0.1; then
		ynh_script_progression "setting starttls false..."
		ynh_write_var_in_file --file=$install_dir/config.ini  --key=smtp_enable_start_tls --value=false
	fi
fi

#=================================================
# UPDATE SYSTEM CONFIGURATION
#=================================================

ynh_script_progression "Updating web server and system service configuration..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="WriteFreely daemon" --log="/var/log/$app/$app.log"

#=================================================
# UPGRADE APP
#=================================================

ynh_script_progression "Upgrading $app..."

pushd $install_dir
	ynh_mysql_db_shell <<< "ALTER DATABASE $db_name CHARACTER SET latin1 COLLATE latin1_swedish_ci;"

	ynh_exec_as_app ./writefreely db migrate
	ynh_exec_as_app ./writefreely --migrate
	ynh_exec_as_app ./writefreely keys generate
popd

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression "Starting $app system service..."

ynh_systemctl --service=$app --action="start" --log_path="systemd" --wait_until="Serving on"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade complete."
